// Per-villager unit textures, generated by recoloring the v2 unit SVGs:
// each peasant gets a skin tone (from its id) and a tunic colored by its job;
// archers/raiders keep their role colors but still vary skin. We pre-rasterize
// every needed (role · skin · tunic) variant once at startup and look them up
// by key — that keeps the per-villager coloring while using the new art.

import type { Texture } from 'pixi.js';
import type { BuildingType, SoldierType } from '../config';
import type { UnitRole } from '../sim/world';
import peasantSvg from '../art/v2/peasant.svg?raw';
import raiderSvg from '../art/v2/raider.svg?raw';
import spearman from '../art/v2/pack/units/spearman.svg?raw';
import manatarms from '../art/v2/pack/units/manatarms.svg?raw';
import pikeman from '../art/v2/pack/units/pikeman.svg?raw';
import knight from '../art/v2/pack/units/knight.svg?raw';
import archer from '../art/v2/pack/units/archer.svg?raw';
import crossbowman from '../art/v2/pack/units/crossbowman.svg?raw';
import camel_lancer from '../art/v2/pack/units/camel_lancer.svg?raw';
import mangonel from '../art/v2/pack/units/mangonel.svg?raw';
import medic from '../art/v2/pack/units/medic.svg?raw';
import standard_bearer from '../art/v2/pack/units/standard_bearer.svg?raw';
import spearmanAtk from '../art/v2/pack/units/spearman_attack.svg?raw';
import manatarmsAtk from '../art/v2/pack/units/manatarms_attack.svg?raw';
import pikemanAtk from '../art/v2/pack/units/pikeman_attack.svg?raw';
import knightAtk from '../art/v2/pack/units/knight_attack.svg?raw';
import archerAtk from '../art/v2/pack/units/archer_attack.svg?raw';
import crossbowmanAtk from '../art/v2/pack/units/crossbowman_attack.svg?raw';
import camelLancerAtk from '../art/v2/pack/units/camel_lancer_attack.svg?raw';
import mangonelAtk from '../art/v2/pack/units/mangonel_attack.svg?raw';
import { rasterizeSvg } from './assets';

const SOLDIER_SVG: Record<SoldierType, string> = {
  spearman, manatarms, pikeman, knight, archer, crossbowman,
  camel_lancer, mangonel, medic, standard_bearer,
};

// Attack-pose art (only the fighters that ship one — not medic/standard-bearer).
const SOLDIER_ATK_SVG: Partial<Record<SoldierType, string>> = {
  spearman: spearmanAtk, manatarms: manatarmsAtk, pikeman: pikemanAtk, knight: knightAtk,
  archer: archerAtk, crossbowman: crossbowmanAtk, camel_lancer: camelLancerAtk, mangonel: mangonelAtk,
};

// Skin tones from the art spec, indexed by `unit.id % SKIN_TONES.length`.
export const SKIN_TONES = [0xf2c9a0, 0xe8b58c, 0xd9a479, 0xc08a5e, 0x9a6a42];

const IDLE_TUNIC = 0x3a5fb5;
const JOB_TUNIC: Partial<Record<BuildingType, number>> = {
  woodcutter: 0x7a4a23,
  appleOrchard: 0x3f9a3f,
  hunter: 0x5f6b2e,
  fishery: 0x2f7d99,
  quarry: 0x7d7a72,
  wheatFarm: 0xcf9a1e,
  mill: 0x9a93a8,
  bakery: 0xd8763a,
  granary: 0xc9a24e,
};
const TUNICS = [IDLE_TUNIC, ...Object.values(JOB_TUNIC)];

export function tunicColorFor(role: UnitRole, jobType: BuildingType | null): number {
  if (role !== 'peasant') return IDLE_TUNIC; // archer/raider tunics are baked in their art
  if (!jobType) return IDLE_TUNIC;
  return JOB_TUNIC[jobType] ?? IDLE_TUNIC;
}

const hex = (n: number): string => `#${(n & 0xffffff).toString(16).padStart(6, '0')}`;
function darken(n: number, f: number): number {
  const r = Math.round(((n >> 16) & 0xff) * f);
  const g = Math.round(((n >> 8) & 0xff) * f);
  const b = Math.round((n & 0xff) * f);
  return (r << 16) | (g << 8) | b;
}
function replaceAll(s: string, from: string, to: string): string {
  return s.split(from).join(to);
}

// Skin tokens used by each source SVG (light + optional shaded variant).
function recolorSkin(svg: string, skin: number): string {
  let out = svg;
  out = replaceAll(out, '#E8B58C', hex(skin)); // peasant + archer skin / head
  out = replaceAll(out, '#E0A87E', hex(darken(skin, 0.92))); // peasant shaded arm
  out = replaceAll(out, '#D9A479', hex(skin)); // raider head
  return out;
}
function recolorTunic(svg: string, tunic: number): string {
  let out = svg;
  out = replaceAll(out, '#3A5FB5', hex(tunic)); // peasant tunic (team-fill)
  out = replaceAll(out, '#2E4C94', hex(darken(tunic, 0.8))); // peasant tunic shade
  return out;
}

export interface UnitTextures {
  anchor: { x: number; y: number };
  get(role: UnitRole, skinIndex: number, tunic: number, attacking?: boolean): Texture;
  /** Stable key for a unit's current appearance, for change detection. */
  key(role: UnitRole, skinIndex: number, tunic: number, attacking?: boolean): string;
}

function keyOf(role: UnitRole, skinIndex: number, tunic: number, attacking = false): string {
  if (role === 'peasant') return `peasant:${skinIndex}:${tunic}`;
  return attacking ? `${role}:atk:${skinIndex}` : `${role}:${skinIndex}`;
}

export async function loadUnitTextures(): Promise<UnitTextures> {
  const srcByRole: Record<UnitRole, string> = {
    peasant: peasantSvg,
    raider: raiderSvg,
    ...SOLDIER_SVG,
  };
  const map = new Map<string, Texture>();

  // Peasants vary skin AND job-tunic; everyone else (raider + soldiers) varies
  // skin only and keeps their baked team/role color.
  const jobs: { role: UnitRole; tunics: number[] }[] = [
    { role: 'peasant', tunics: TUNICS },
    { role: 'raider', tunics: [IDLE_TUNIC] },
    ...(Object.keys(SOLDIER_SVG) as SoldierType[]).map((role) => ({ role, tunics: [IDLE_TUNIC] })),
  ];

  const tasks: Promise<void>[] = [];
  for (const { role, tunics } of jobs) {
    for (let s = 0; s < SKIN_TONES.length; s++) {
      for (const tunic of tunics) {
        const k = keyOf(role, s, tunic);
        if (!map.has(k)) {
          let svg = recolorSkin(srcByRole[role], SKIN_TONES[s]);
          if (role === 'peasant') svg = recolorTunic(svg, tunic);
          tasks.push(rasterizeSvg(svg).then((tex) => void map.set(k, tex)));
        }
      }
      // attack-pose variant for the fighters that ship one
      const atkSvg = SOLDIER_ATK_SVG[role as SoldierType];
      if (atkSvg) {
        const ak = keyOf(role, s, IDLE_TUNIC, true);
        if (!map.has(ak)) {
          tasks.push(rasterizeSvg(recolorSkin(atkSvg, SKIN_TONES[s])).then((tex) => void map.set(ak, tex)));
        }
      }
    }
  }
  await Promise.all(tasks);

  const fallback = map.get(keyOf('peasant', 0, IDLE_TUNIC))!;
  const lookup = (role: UnitRole, skinIndex: number, tunic: number, attacking = false): Texture =>
    map.get(keyOf(role, skinIndex, tunic, attacking)) ??
    map.get(keyOf(role, skinIndex, tunic, false)) ?? // no attack pose → standing
    fallback;
  return {
    anchor: { x: 17, y: 46 },
    key: keyOf,
    get: lookup,
  };
}
