// Per-villager unit textures, generated by recoloring the v2 unit SVGs:
// each peasant gets a skin tone (from its id) and a tunic colored by its job;
// archers/raiders keep their role colors but still vary skin. We pre-rasterize
// every needed (role · skin · tunic) variant once at startup and look them up
// by key — that keeps the per-villager coloring while using the new art.

import type { Texture } from 'pixi.js';
import type { BuildingType } from '../config';
import type { UnitRole } from '../sim/world';
import peasantSvg from '../art/v2/peasant.svg?raw';
import archerSvg from '../art/v2/archer.svg?raw';
import raiderSvg from '../art/v2/raider.svg?raw';
import { rasterizeSvg } from './assets';

// Skin tones from the art spec, indexed by `unit.id % SKIN_TONES.length`.
export const SKIN_TONES = [0xf2c9a0, 0xe8b58c, 0xd9a479, 0xc08a5e, 0x9a6a42];

const IDLE_TUNIC = 0x3a5fb5;
const JOB_TUNIC: Partial<Record<BuildingType, number>> = {
  woodcutter: 0x7a4a23,
  appleOrchard: 0x3f9a3f,
  hunter: 0x5f6b2e,
  fishery: 0x2f7d99,
  quarry: 0x7d7a72,
  wheatFarm: 0xcf9a1e,
  mill: 0x9a93a8,
  bakery: 0xd8763a,
  granary: 0xc9a24e,
};
const TUNICS = [IDLE_TUNIC, ...Object.values(JOB_TUNIC)];

export function tunicColorFor(role: UnitRole, jobType: BuildingType | null): number {
  if (role !== 'peasant') return IDLE_TUNIC; // archer/raider tunics are baked in their art
  if (!jobType) return IDLE_TUNIC;
  return JOB_TUNIC[jobType] ?? IDLE_TUNIC;
}

const hex = (n: number): string => `#${(n & 0xffffff).toString(16).padStart(6, '0')}`;
function darken(n: number, f: number): number {
  const r = Math.round(((n >> 16) & 0xff) * f);
  const g = Math.round(((n >> 8) & 0xff) * f);
  const b = Math.round((n & 0xff) * f);
  return (r << 16) | (g << 8) | b;
}
function replaceAll(s: string, from: string, to: string): string {
  return s.split(from).join(to);
}

// Skin tokens used by each source SVG (light + optional shaded variant).
function recolorSkin(svg: string, skin: number): string {
  let out = svg;
  out = replaceAll(out, '#E8B58C', hex(skin)); // peasant + archer skin / head
  out = replaceAll(out, '#E0A87E', hex(darken(skin, 0.92))); // peasant shaded arm
  out = replaceAll(out, '#D9A479', hex(skin)); // raider head
  return out;
}
function recolorTunic(svg: string, tunic: number): string {
  let out = svg;
  out = replaceAll(out, '#3A5FB5', hex(tunic)); // peasant tunic (team-fill)
  out = replaceAll(out, '#2E4C94', hex(darken(tunic, 0.8))); // peasant tunic shade
  return out;
}

export interface UnitTextures {
  anchor: { x: number; y: number };
  get(role: UnitRole, skinIndex: number, tunic: number): Texture;
  /** Stable key for a unit's current appearance, for change detection. */
  key(role: UnitRole, skinIndex: number, tunic: number): string;
}

function keyOf(role: UnitRole, skinIndex: number, tunic: number): string {
  return role === 'peasant' ? `peasant:${skinIndex}:${tunic}` : `${role}:${skinIndex}`;
}

export async function loadUnitTextures(): Promise<UnitTextures> {
  const srcByRole: Record<UnitRole, string> = {
    peasant: peasantSvg,
    archer: archerSvg,
    raider: raiderSvg,
  };
  const map = new Map<string, Texture>();

  const jobs: { role: UnitRole; tunics: number[] }[] = [
    { role: 'peasant', tunics: TUNICS },
    { role: 'archer', tunics: [IDLE_TUNIC] },
    { role: 'raider', tunics: [IDLE_TUNIC] },
  ];

  const tasks: Promise<void>[] = [];
  for (const { role, tunics } of jobs) {
    for (let s = 0; s < SKIN_TONES.length; s++) {
      for (const tunic of tunics) {
        const k = keyOf(role, s, tunic);
        if (map.has(k)) continue;
        let svg = recolorSkin(srcByRole[role], SKIN_TONES[s]);
        if (role === 'peasant') svg = recolorTunic(svg, tunic);
        tasks.push(rasterizeSvg(svg).then((tex) => void map.set(k, tex)));
      }
    }
  }
  await Promise.all(tasks);

  const fallback = map.get(keyOf('peasant', 0, IDLE_TUNIC))!;
  return {
    anchor: { x: 17, y: 46 },
    key: keyOf,
    get: (role, skinIndex, tunic) => map.get(keyOf(role, skinIndex, tunic)) ?? fallback,
  };
}
